import 'package:shared_preferences/shared_preferences.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:device_info_plus/device_info_plus.dart';
import 'package:path_provider/path_provider.dart';
import 'dart:io';
import 'package:uuid/uuid.dart';
import '../models/device_model.dart';
import '../models/transfer_model.dart';

class StorageService {
  static final StorageService _instance = StorageService._internal();
  factory StorageService() => _instance;
  StorageService._internal();

  late SharedPreferences _prefs;
  late Box<TransferModel> _transferBox;

  bool _initialized = false;

  Future<void> init() async {
    if (_initialized) return;

    await Hive.initFlutter();
    Hive.registerAdapter(DeviceModelAdapter());
    Hive.registerAdapter(TransferModelAdapter());
    _transferBox = await Hive.openBox<TransferModel>('transfers');

    _prefs = await SharedPreferences.getInstance();
    _initialized = true;
  }

  // --- Device ID ---
  String get deviceId {
    final id = _prefs.getString('deviceId');
    if (id != null) return id;
    final newId = const Uuid().v4();
    _prefs.setString('deviceId', newId);
    return newId;
  }

  // --- Device Name ---
  String get deviceName {
    final name = _prefs.getString('deviceName');
    if (name != null) return name;
    return 'EchoDevice';
  }

  set deviceName(String name) {
    if (name.trim().length > 30) {
      _prefs.setString('deviceName', name.trim().substring(0, 30));
    } else {
      _prefs.setString('deviceName', name.trim());
    }
  }

  Future<String> _getDefaultDeviceName() async {
    final deviceInfo = DeviceInfoPlugin();
    if (Platform.isAndroid) {
      final androidInfo = await deviceInfo.androidInfo;
      return androidInfo.model;
    } else if (Platform.isIOS) {
      final iosInfo = await deviceInfo.iosInfo;
      return iosInfo.name;
    }
    return 'EchoDevice';
  }

  // --- Default Save Path ---
  String get defaultSavePath {
    final path = _prefs.getString('defaultSavePath');
    if (path != null && Directory(path).existsSync()) return path;
    // default to Downloads/echoSystem
    final downloads = _getDownloadsPath();
    final dir = Directory('$downloads/echoSystem');
    if (!dir.existsSync()) dir.createSync();
    _prefs.setString('defaultSavePath', dir.path);
    return dir.path;
  }

  set defaultSavePath(String path) {
    _prefs.setString('defaultSavePath', path);
  }

  String _getDownloadsPath() {
    if (Platform.isAndroid) {
      return '/storage/emulated/0/Download';
    } else if (Platform.isIOS) {
      // iOS doesn't have a standard Downloads folder; use app documents
      return getApplicationDocumentsDirectory().path;
    }
    return Directory.current.path;
  }

  // --- Avatar Color ---
  int get avatarColor => _prefs.getInt('avatarColor') ?? 0xFF4A5B6E;
  set avatarColor(int color) => _prefs.setInt('avatarColor', color);

  // --- Notifications Enabled ---
  bool get notificationsEnabled => _prefs.getBool('notifications') ?? true;
  set notificationsEnabled(bool value) => _prefs.setBool('notifications', value);

  // --- Transfer History ---
  List<TransferModel> get transferHistory {
    return _transferBox.values.toList();
  }

  Future<void> addTransfer(TransferModel transfer) async {
    await _transferBox.put(transfer.id, transfer);
    // Cap history to 500 entries
    if (_transferBox.length > 500) {
      final oldestKeys = _transferBox.keys.take(_transferBox.length - 500).toList();
      for (var key in oldestKeys) {
        await _transferBox.delete(key);
      }
    }
  }

  Future<void> updateTransfer(TransferModel transfer) async {
    await _transferBox.put(transfer.id, transfer);
  }

  Future<void> deleteTransfer(String id) async {
    await _transferBox.delete(id);
  }

  Future<void> clearTransferHistory() async {
    await _transferBox.clear();
  }

  // --- Helper adapters (required for Hive) ---
  // These are minimal stubs; actual adapters will be generated by Hive generator.
  // For now, we'll define them manually to avoid build_runner.
  void dispose() {
    _transferBox.close();
  }
}

// Minimal manual adapters (to avoid generation until Phase 5A)
class DeviceModelAdapter extends TypeAdapter<DeviceModel> {
  @override
  final int typeId = 0;
  @override
  DeviceModel read(BinaryReader reader) {
    return DeviceModel(
      id: reader.readString(),
      name: reader.readString(),
      ipAddress: reader.readString(),
      port: reader.readInt(),
      isOnline: reader.readBool(),
      avatarColor: reader.readInt(),
      lastSeen: DateTime.fromMillisecondsSinceEpoch(reader.readInt()),
    );
  }
  @override
  void write(BinaryWriter writer, DeviceModel obj) {
    writer.writeString(obj.id);
    writer.writeString(obj.name);
    writer.writeString(obj.ipAddress);
    writer.writeInt(obj.port);
    writer.writeBool(obj.isOnline);
    writer.writeInt(obj.avatarColor);
    writer.writeInt(obj.lastSeen.millisecondsSinceEpoch);
  }
}

class TransferModelAdapter extends TypeAdapter<TransferModel> {
  @override
  final int typeId = 1;
  @override
  TransferModel read(BinaryReader reader) {
    return TransferModel(
      id: reader.readString(),
      fileName: reader.readString(),
      fileSizeBytes: reader.readInt(),
      transferredBytes: reader.readInt(),
      status: reader.readString(),
      direction: reader.readString(),
      peerId: reader.readString(),
      peerName: reader.readString(),
      startedAt: DateTime.fromMillisecondsSinceEpoch(reader.readInt()),
      completedAt: reader.readBool() ? DateTime.fromMillisecondsSinceEpoch(reader.readInt()) : null,
      localPath: reader.readBool() ? reader.readString() : null,
    );
  }
  @override
  void write(BinaryWriter writer, TransferModel obj) {
    writer.writeString(obj.id);
    writer.writeString(obj.fileName);
    writer.writeInt(obj.fileSizeBytes);
    writer.writeInt(obj.transferredBytes);
    writer.writeString(obj.status);
    writer.writeString(obj.direction);
    writer.writeString(obj.peerId);
    writer.writeString(obj.peerName);
    writer.writeInt(obj.startedAt.millisecondsSinceEpoch);
    writer.writeBool(obj.completedAt != null);
    if (obj.completedAt != null) writer.writeInt(obj.completedAt!.millisecondsSinceEpoch);
    writer.writeBool(obj.localPath != null);
    if (obj.localPath != null) writer.writeString(obj.localPath!);
  }
}
